name: 'Consolidate JSON'
description: 'A GitHub Action to consolidate JSON files'
inputs:
  token:
    description: 'GitHub Token'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  color: 'green'
  icon: 'package'
